version: "3.8"

services:
  django:
    build: .
    container_name: user-service
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - db-user
  
  db-user:
    image: postgres
    container_name: db-user
    environment:
      - POSTGRES_DB=user
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0089ashi
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata: